# Generated by Django 5.1.1 on 2024-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_remove_detallefactura_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
